[profile.default]
src = "contracts/src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
evm_version = "paris"
ffi = false

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"

[profile.test]
fs_permissions = [{ access = "read", path = "./" }]
